#!/usr/bin/env python3
"""
Setup script for Alpaca Trading Analytics
Helps users configure the application with their API keys
"""

import os
import sys
from pathlib import Path

def setup_config():
    """Interactive setup for API configuration."""
    print("🚀 Alpaca Trading Analytics Setup")
    print("=" * 50)
    
    # Check if config already exists
    config_file = Path("config.py")
    if config_file.exists():
        response = input("⚠️  config.py already exists. Overwrite? (y/n): ")
        if response.lower() not in ['y', 'yes']:
            print("Setup cancelled.")
            return
    
    print("\n🔑 API Key Configuration")
    print("Get your API keys from: https://app.alpaca.markets/")
    print("📝 Note: These keys will be stored in config.py")
    
    # Get API keys
    api_key = input("\n📋 Enter your Alpaca API Key: ").strip()
    secret_key = input("🔐 Enter your Alpaca Secret Key: ").strip()
    
    if not api_key or not secret_key:
        print("❌ Error: Both API key and secret key are required.")
        return
    
    # Choose environment
    print("\n🎯 Trading Environment:")
    print("1. Paper Trading (recommended for testing)")
    print("2. Live Trading (real money)")
    
    while True:
        choice = input("Select environment (1 or 2): ").strip()
        if choice in ['1', '2']:
            use_paper = choice == '1'
            break
        print("Please enter 1 or 2")
    
    # Create config file
    config_content = f'''"""
Alpaca Trading Analytics Configuration
Generated by setup script
"""

# Alpaca API Configuration
ALPACA_API_KEY = "{api_key}"
ALPACA_SECRET_KEY = "{secret_key}"

# Trading Environment
USE_PAPER_TRADING = {use_paper}

# Analysis Configuration
DEFAULT_ANALYSIS_PERIODS = ["1M", "3M", "1Y", "1W", "1D"]
MAX_ORDERS_TO_FETCH = 100
ANALYSIS_START_DATE = None  # Or "2024-04-11" for specific start date

# API Configuration
MAX_RETRIES = 3
RETRY_DELAY = 1.0

# Output formatting
CURRENCY_SYMBOL = "$"
DATE_FORMAT = "%Y-%m-%d %H:%M:%S UTC"
PRECISION_DECIMAL_PLACES = 2

# Chart Generation Settings
CHART_DPI = 300  # High resolution for professional output
CHART_STYLE = "seaborn-v0_8"  # Professional styling
AUTO_OPEN_CHARTS = True  # Automatically open generated charts
'''
    
    try:
        with open(config_file, 'w') as f:
            f.write(config_content)
        
        print(f"\n✅ Configuration saved to {config_file}")
        print(f"🎯 Environment: {'Paper Trading' if use_paper else 'Live Trading'}")
        
        # Update .gitignore to include config.py
        gitignore_file = Path(".gitignore")
        if gitignore_file.exists():
            with open(gitignore_file, 'r') as f:
                content = f.read()
            
            if "config.py" not in content:
                with open(gitignore_file, 'a') as f:
                    f.write("\n# Local configuration\nconfig.py\n")
                print("📝 Added config.py to .gitignore for security")
        
        print("\n🚀 Setup complete! You can now run:")
        print("   python alpaca.py                    # Full analysis with charts")
        print("   python alpaca.py --test-charts      # Test chart generation")
        print("\n📊 Features available:")
        print("   • Comprehensive performance analytics")
        print("   • Professional chart generation")
        print("   • Risk-adjusted metrics")
        print("   • Trade analysis and statistics")
        print("   • High-resolution PNG output")
        
    except Exception as e:
        print(f"❌ Error creating config file: {e}")

def install_dependencies():
    """Install required dependencies."""
    import subprocess
    
    print("📦 Installing dependencies...")
    
    try:
        # Install core dependencies
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        print("✅ All dependencies installed successfully")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to install dependencies: {e}")
        print("💡 Try running manually: pip install -r requirements.txt")
        return False

def check_dependencies():
    """Check if required dependencies are installed."""
    missing_deps = []
    
    # Core dependencies
    try:
        import requests
    except ImportError:
        missing_deps.append("requests")
    
    # Chart generation dependencies
    try:
        import matplotlib
        import seaborn
        import pandas
        import numpy
        import scipy
        print("✅ All dependencies satisfied (including chart generation)")
        charts_available = True
    except ImportError as e:
        print(f"⚠️  Chart dependencies missing: {e}")
        print("📊 Charts will not be available without these packages")
        charts_available = False
    
    if missing_deps:
        print(f"❌ Missing core dependencies: {', '.join(missing_deps)}")
        response = input("📦 Install missing dependencies now? (y/n): ")
        if response.lower() in ['y', 'yes']:
            return install_dependencies()
        else:
            print("⚠️  Some features may not work without dependencies")
            return False
    
    if not charts_available:
        response = input("📊 Install chart generation dependencies? (y/n): ")
        if response.lower() in ['y', 'yes']:
            return install_dependencies()
    
    return True

def main():
    """Main setup function."""
    print("🔍 Checking dependencies...")
    
    if not check_dependencies():
        sys.exit(1)
    
    setup_config()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n👋 Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        sys.exit(1)
